version: '3'

services:
  app:
    build: .

    volumes:
      - /localdirectory/path:/app/data

    env_file:
      -  ./command.env    
    
    command: python3 kafka-latency-profiler.py --env_file ./command.env
