version: '3'

services:
  app:
    build: .

    volumes:
      - <localfilepath>:/app/data 
    
    env_file:
      - <filepath to arguments.env>
      

    command: python3 kafka-latency-profiler.py
