version: '3'

services:
  app:
    build: .

    volumes:
      - /home/arunherga/eve:/app/data 
    
    env_file:
      - /home/arunherga/eve/arguments.env
      

    command: python3 kafka-latency-profiler.py
