version: '3'

services:
  app:
    
    build: .

    env_file:
      -  ./command.env    
    
    command: python3 kafka-latency-profiler.py --consumer_config_file ${CONSUMER_CONFIG_FILE} --input_topic ${INPUT_TOPIC} --group_id ${GROUP_ID} --consumer_output ${CONSUMER_OUTPUT} --output_topic ${OUTPUT_TOPIC} --value_deserializer ${VALUE_DESERIALIZER} --run_interval ${RUN_INTERVAL} --t1 ${T1} --t2 ${T2} --producer_config_file ${PRODUCER_CONFIG_FILE} --enable_sampling ${ENABLE_SAMPLING}
    #command: python3 kafka-latency-profiler.py --consumer_config_file ./client.properties --input_topic json_schema --group_id group106 --consumer_output dumpToTopic --output_topic topic_12 --value_deserializer JSONSchemaDeserializer --run_interval 15 --t1 value.ordertime --t2 consumerWallClockTime --producer_config_file ./producer.properties
    #command: python3 kafka-latency-profiler.py -h