version: '3'

services:
  app:
    build: .

    volumes:
      - /home/arunherga/eve:/app/data

    env_file:
      -  ./command.env    
    
    command: python3 kafka_latency_profiler.py --env_file ./command.env